service:
  name: lambda-genetics

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 256
  timeout: 30
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "*"

functions:
  kicker: 
    handler: src/handlers/index.kicker
    events:
      - http:
          method: get
          path: hello
  
  looper:
    handler: src/handlers/index.looper

  aggregate:
    handler: src/handlers/index.aggregate

  calculate:
    handler: src/handlers/index.calculate
  
  populate:
    handler: src/handlers/index.populate
