service:
  name: lambda-genetics

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 256
  timeout: 60
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "*"

functions:
  generation:
    handler: handler.generation
    events:
      - http:
          method: get
          path: hello

  calculate:
    handler: handler.calculate
